# Generated by Django 4.0.5 on 2022-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsekeer', '0002_alter_job_sekeer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_sekeer',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('NOT TO SAY', 'NOT TO SAY')], default='Not Selected', max_length=20),
        ),
    ]
