# Generated by Django 4.0.5 on 2022-07-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobposter', '0003_alter_job_post_job_type'),
        ('jobsekeer', '0003_alter_job_sekeer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_sekeer',
            name='gender',
            field=models.CharField(choices=[('NOT TO SAY', 'NOT TO SAY'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='Not Selected', max_length=20),
        ),
        migrations.CreateModel(
            name='BookMarked_Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobposter.job_post', verbose_name='title')),
                ('job_sekeer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobsekeer.job_sekeer', verbose_name='name')),
            ],
        ),
    ]
