# Generated by Django 4.0.5 on 2022-07-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsekeer', '0005_alter_bookmarked_jobs_job_sekeer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_sekeer',
            name='gender',
            field=models.CharField(choices=[('NOT TO SAY', 'NOT TO SAY'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='Not Selected', max_length=20),
        ),
    ]
