# Generated by Django 4.0.5 on 2022-07-01 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='applied_candidate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_post',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 7, 1)),
        ),
        migrations.AddField(
            model_name='job_post',
            name='description',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_opening',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_role',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_type',
            field=models.CharField(choices=[('non-tech', 'non-tech'), ('tech', 'tech')], default='tech', max_length=20),
        ),
        migrations.AddField(
            model_name='job_post',
            name='salary_package',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
