# Generated by Django 4.0.5 on 2022-07-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposter', '0003_alter_job_post_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_type',
            field=models.CharField(choices=[('non-tech', 'non-tech'), ('tech', 'tech')], default='tech', max_length=20),
        ),
    ]
